services:
  db:
    image: postgres:16
    container_name: rebalancer_db
    restart: always
    environment:
      POSTGRES_USER: rebalancer_user
      POSTGRES_PASSWORD: rebalancer_pw
      POSTGRES_DB: rebalancer
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
